export default {
	Ash: require("../../assets/legendIcons/Ash.svg").default,
	Bangalore: require("../../assets/legendIcons/Bangalore.svg").default,
	Bloodhound: require("../../assets/legendIcons/Bloodhound.svg").default,
	Caustic: require("../../assets/legendIcons/Caustic.svg").default,
	Crypto: require("../../assets/legendIcons/Crypto.svg").default,
	Fuse: require("../../assets/legendIcons/Fuse.svg").default,
	Gibraltar: require("../../assets/legendIcons/Gibraltar.svg").default,
	Horizon: require("../../assets/legendIcons/Horizon.svg").default,
	Lifeline: require("../../assets/legendIcons/Lifeline.svg").default,
	Loba: require("../../assets/legendIcons/Loba.svg").default,
	Mirage: require("../../assets/legendIcons/Mirage.svg").default,
	Octane: require("../../assets/legendIcons/Octane.svg").default,
	Pathfinder: require("../../assets/legendIcons/Pathfinder.svg").default,
	Rampart: require("../../assets/legendIcons/Rampart.svg").default,
	Revenant: require("../../assets/legendIcons/Revenant.svg").default,
	Seer: require("../../assets/legendIcons/Seer.svg").default,
	Valkyrie: require("../../assets/legendIcons/Valkyrie.svg").default,
	Wattson: require("../../assets/legendIcons/Wattson.svg").default,
	Wraith: require("../../assets/legendIcons/Wraith.svg").default,
}